name: Build Executable
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        
    - name: Install dependencies
      run: pip install pyinstaller
      
    - name: Build EXE
      run: pyinstaller --onefile src/main.py --name MyApp
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-Windows
        path: dist/MyApp.exe
