name: Cross-Platform Build
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false  # ✅ 此处缩进与 matrix 同级
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: main-repo

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'main-repo/requirements.txt'

    - name: Install Dependencies
      run: |
        cd main-repo
        pip install -r requirements.txt

    - name: Build Executable
      working-directory: ./main-repo
      run: |
        pyinstaller --onefile src/main.py \
          --add-data "assets/app_icon.ico:assets/" \
          --add-data ".env:." \
          --name TextGenerator

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Build-${{ matrix.os }}
        path: main-repo/dist/*
