name: Build Executable
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install pyinstaller
      
    - name: Build EXE
      run: pyinstaller --onefile src/文本生成器.py --name 文本生成器
      
    - name: Upload artifact
    # 使用动态文件名
    - uses: actions/upload-artifact@v4
      with:
        name: MyApp-${{ env.VERSION }}-${{ runner.os }}
        path: dist/*
